---
abstract: 'Basic DNA utilities'
author:
  - 'Kevin Galinsky <kgalinsky plus cpan at mail dot com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Util-DNA
provides:
  Bio::Util::DNA:
    file: lib/Bio/Util/DNA.pm
    version: v0.2.1
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.1
